import "./globals.css";
import { Inter } from "next/font/google";
import Provider from "./components/provider";
import Nav from "./components/nav";
import { MovieProvider } from "./components/movieprovider";
import { SideNav } from "./components/sidenav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <MovieProvider>
          <body className={`${inter.className} max-w-screen`}>
            <Nav />
            <SideNav />
            <div className="h-full ml-60 ">{children}</div>
          </body>
        </MovieProvider>
      </Provider>
    </html>
  );
}
